### ISSUE TITLE
Deprecated getImages() in product variant

### ISSUE THREAD

**Issue by maedchenflohmarkt** [aboutyou/aboutyou-php-sdk#4]
We just updated the SDK and in the latest version (do not know since when) getImages() on the Variant class is deprecated and recommends to use getImage() on the Product directly.

However getImages() on the Product returns just one image for us and not all 5.

Any idea how to fix this? Is this a bug in the SDK or a missing call/parameter when fetching the products?

**Comment by jniebuhr** [comment]
The Variant::getImages() is indeed deprecated in favor of Product::getImages().
To get those images you will need to request another field.
I will leave this open since this field is missing from the ProductFields class.
When you set the fields you need, simply add a field called 'images'.
The method should return images then.

**Comment by jniebuhr** [comment]
@christianblos Please add the images field to ProductFields. We should also add something to the deprecation notice of Variant::getImages that explains this behavior.

**Comment by christianblos** [comment]
Done! You can find the new field constant in version 2.6.11
